sudo: false
language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo build -- --features std &&
      travis-cargo test -- --features std &&
      travis-cargo --only stable doc -- --features std

after_success:
  - travis-cargo --only stable doc-upload

env:
  global:
    - secure: Q3dmNxc18eSye7TV1kzijQsdp9oeMQ8xxTqshMOLLVxtTBfJwIYcPwAhk4bGWZpa6DbNZHSQTfvWPY2lt1kaNXXurQQKYOAUgtPjnFwJg7uOIHtph7HEVB+pybKYZ2usFMWfnFP1SfojNSYjpaR1mnjJJZNTWrJdmKUbhoyJTuc=

branches:
  only:
    - auto
    - master

notifications:
  email:
    on_success: never
  webhooks: http://homu.herokuapp.com/travis
