language: rust
sudo: false

env:
  global:
    - secure: Q3dmNxc18eSye7TV1kzijQsdp9oeMQ8xxTqshMOLLVxtTBfJwIYcPwAhk4bGWZpa6DbNZHSQTfvWPY2lt1kaNXXurQQKYOAUgtPjnFwJg7uOIHtph7HEVB+pybKYZ2usFMWfnFP1SfojNSYjpaR1mnjJJZNTWrJdmKUbhoyJTuc=

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master
